---
title: "Untitled"
author: "Nathan Brouwer"
date: "February 19, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 


#### Reshape by migratory status 



```{r}
summary(factor(ann_caps$status.focals))
ann_caps[is.na(ann_caps$status.focals),"spp.code"]


ann_caps$hab1 <- as.character(ann_caps$hab1)
ann_caps$hab1 <- gsub("D$","DF",ann_caps$hab1)
summary(factor(ann_caps$hab1 ))
hab_matrix <- dcast(data = ann_caps,
      formula = site + year + 
                year.num + site.age + 
                site.age.init + 
                site.age.cent ~ hab1,
      value.var = "spp.code",
        fun.aggregate = length)
#names(hab_matrix)[dim(hab_matrix)[2]] <- "hab.NA"
hab.tot <- apply(hab_matrix[,c("DF","EF","SF")],1,sum)


diet_matrix <- dcast(data = ann_caps,
      formula = site + year + 
                year.num + site.age + 
                site.age.init + 
                site.age.cent ~ diet,
      value.var = "spp.code",
        fun.aggregate = length)
#names(diet_matrix)[dim(diet_matrix)[2]] <- "diet.NA"

diets <- c("C","F","G","I","N","O")
diet.tot <- apply(diet_matrix[,diets],1,sum)

trait_dat <- cbind(hab_matrix,
                   diet_matrix[,diets])

#check that row totals match
plot(diet.tot , hab.tot)

habs <- c("DF","EF","SF")
names(trait_dat)[which(names(trait_dat) %in% habs)] <- paste("hab",habs,sep = ".")
names(trait_dat)[which(names(trait_dat) %in% diets)] <- paste("diet",diets,sep = ".")


trait_dat$tot <- diet.tot
```
