---
title: "Analysis: sex & age ratio - regression"
author: "Nathan Brouwer"
date: "January 17, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




### Base model - age ratio

```{r}
# ann_caps4$spp.code <- as.character(ann_caps4$spp.code)
# ann_caps4$year <- as.character(ann_caps4$year)
# ann_caps4$site <- as.character(ann_caps4$site)

m.age0 <- bglmer(age.AHY.01 ~ 1 +
               #(1|band) +
               (1|year) +
               (1|site) +
               (1|spp.code) +
               (1|spp.code:site),
              data = ann_caps4[,],
              family = binomial#,
              #glmerControl(optimizer = "Nelder_Mead")
              )
```











```{r}
m.age0@frame$ID <- with(m.age0@frame,
                        paste( spp.code, site))

i <- match(unique(m.age0@frame$ID),m.age0@frame$ID)

dat.new <- m.age0@frame[i,]
x <- predictInterval(m.age0 ,
                newdata = dat.new,
                which = "random",
                level = 0.95,
                n.sims = 100,
                stat = "median")

dat.new2 <- cbind(dat.new[c("year","spp.code","site")], x)

dat.new2$fit.real <- invlogit(dat.new2$fit)
dat.new2$upr.real <- invlogit(dat.new2$upr)
dat.new2$lwr.real <- invlogit(dat.new2$lwr)
```




```{r}
dat.new2$site <- factor(dat.new2$site,
                        levels = c("La Cueva","La Caoba","Morelia","El Corral",
                                   "Aceitillar"))
dat.new2$spp.code <- factor(dat.new2$spp.code,
                            levels = focals)
ggplot(data = dat.new2,
       aes(y = fit.real,
           x = site)) +
  geom_point() +
  facet_wrap(~spp.code) 
```




```{r}
summary(factor(ann_caps4$site))
# newdat <- expand.grid(age.AHY.01 = NA,
#                       year = unique(m.age0@frame$year),
#                       spp.code = unique(m.age0@frame$spp.code),
#                       site = unique(m.age0@frame$site)
#                       )


easyPredCI(m.age0)





length(i)
length(m.age0@frame$ID)

preds <- predict(m.age0, newdata = m.age0@frame[i,], 
                re.form = ~(1|spp.code) + (1|spp.code:site))

#extract matching 
dat.out <- m.age0@frame[i, ]

dat.out$preds <- preds


with(dat.out, table(spp.code, site))

```












## Model predictors
```{r}
## diet groups
### normal parameterization
m.age.diet <- update(m.age0, . ~ . + diet)
m.age.dietXsite <- update(m.age0, . ~ . + diet*site)

### mean parameterization
m.age2.dietXsite.means <- bglmer(age.AHY.01 ~ -1 + site:diet +
               (1|year) +
               (1|spp.code),
              data = ann_caps4[-i.Aceitillar,],
              family = binomial)

## habitat affinities
m.age.hab <- update(m.age0, . ~ . + hab1)
m.age.habXsite <- update(m.age0, . ~ . + hab1*site)

### mean parameterization
m.age.habXsite.means <- bglmer(age.AHY.01 ~ -1 + site:hab1 +
               (1|year) +
               (1|spp.code),
              data = ann_caps4[-i.Aceitillar,],
              family = binomial)




## status: res vs. migrant
m.age.stat <- update(m.age0, . ~ . + status.focals)
m.age.statXsite <- update(m.age0, . ~ . + status.focals*site)

### mean parameterization
m.age.statXsite.means <- bglmer(age.AHY.01 ~ -1 + site:status.focals +
               (1|year) +
               (1|spp.code),
              data = ann_caps4[-i.Aceitillar,],
              family = binomial)
```

```{r}
coefplot(m.age.dietXsite.means)
```

```{r}
coefplot(m.age.habXsite.means)
```


```{r}
coefplot(m.age.statXsite.means)
```


```{r}
AICtab(m.age0,
       m.age.diet, 
       m.age.dietXsite,
       m.age2.dietXsite.means,
       
       m.age.hab,
       m.age.habXsite,
       m.age.habXsite.means
       )
```


```{r}
AICtab(m.age0,
       m.age1, m.age1b,
       m.age2, 
       m.age3, m.age3b,
       m.age4, m.age4b)
```


```{r}
plot_model(m.age4)
```


# plot Age Ratio

```{r}
pd <- position_dodge(0.1)
ggplot(data = ann_caps.focals[i.use,],
       aes(y = as.numeric(age.AHY.01)-1,
           x = site.age), 
       color = site,
       group = status.focals) +
  geom_jitter(aes(color = site), height = 0.1) +
  facet_wrap(~ status.focals) + 
  geom_smooth(method = glm,
              method.args = list(family = "binomial")) +
  ylab("Age Ratio") + theme_bw()

```




















## Analysis of sex ratio


```{r}
library(lme4)

ann_caps.focals2$ID <- with(ann_caps.focals2, paste(band, spp.code))

#i.use <- which(ann_caps.focals2$site.age > 0)



dim(ann_caps.focals)
length(i.use)
m0 <- glmer(sex.M ~ 1 +
               #(1|ID) +
               (1|year) +
               (1|site) +
               (1|spp.code),
              data = ann_caps.focals2[i.use,],
              family = binomial)

```


```{r}
m1 <- update(m0, . ~ . + site.age)
m2 <- update(m0, . ~ . +            status.focals)
m3 <- update(m0, . ~ . + site.age + status.focals)
m4 <- update(m0, . ~ . +                          site.age*status.focals)
```


```{r}
AICtab(m0, m1, m2, m3, m4)
```

```{r}
summary(m3)
```

