---
title: "Untitled"
author: "Nathan Brouwer"
date: "February 27, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Libraries
```{r}
library(ggplot2)
library(cowplot)
```


## Load plots

```{r}
load(file = "gg_flying_insects_regression.RData")
load(file = "gg_flying_insects_anova.RData")
load(file = "gg_litter_insects_regression.RData")
load(file = "gg_litter_insects_anova.RData")
```


Tweak axes labels
```{r}
gg.out.fly.reg2 <- gg.out.fly.reg2 +xlab("") +
  theme(axis.text.x=element_blank()) +
  ggtitle("")

gg.anova.fly2 <- gg.anova.fly2 +xlab("") +
  theme(axis.text.x=element_blank()) +
  ggtitle("")

gg.litter.regress2 <- gg.litter.regress2 + ggtitle("")
gg.anova.litter <-  gg.anova.litter + ggtitle("")
```


```{r}
cowplot::plot_grid(gg.out.fly.reg2,
                   gg.anova.fly2,
                   gg.litter.regress2,
                   gg.anova.litter,
                   rel_widths = c(8,1),
                   labels = c("a","","b",""))




```

