---
title: "Make final version of table 5 and 6"
author: "Nathan Brouwer"
date: "January 26, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


Merge age/sex/sample size df with site persistenc df

## Libraries

```{r}

library(here)
```


## Load data

```{r}
tables5.6.final_age_etc <- read.csv(file = "./tables/temp_tables_5_6_age_etc.csv")
tables5.6.final_site_persist <- read.csv( "./tables/temp_tables_5_6_site_persist.csv")

```

## Set spp order for tables
names of species
```{r}
focal.mig <- c("OVEN","BAWW","COYE","AMRE","CMWA",
               "BTBW","PAWA","PRAW")

focal.res <- c("HILC" # formerly HLCU
,"STOF"
,"RLTH"
,"NOMO"
,"GTGT"   # formerly GRWA
,"BANA"
,"BCPT"
,"YFGR"
,"BFGR"
,"GABU")

focals <- c(focal.mig,focal.res)
```


replicate order from  tables in oridingal MS

```{r}
tables5.6.final_age_etc$spp.code <- factor(tables5.6.final_age_etc$spp.code,
                             levels = focals)
tables5.6.final_site_persist$spp.code <- factor(tables5.6.final_site_persist$spp.code,
                             levels = focals)

```


###
```{r}
which(focals %in% tables5.6.final_age_etc$spp.code)
```


## Merge tables

```{r}
tables5.6 <- merge(tables5.6.final_age_etc,
      tables5.6.final_site_persist,by = "spp.code",sort = F)
```




## Save output

```{r}
write.csv(tables5.6, file = "./tables/tables5_6.csv")
```


```{r}
# sjt.df(tables5.6, 
#        describe = F,
#        file = "temp.doc")
```

